services:
  nginx:
    build: requirements/nginx
    image: nginx:oo
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart:
      - on_failure

  wordpress:
    build: requirements/mariadb
    image: wordpress:oo
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart:
      - on_failure
  
  mariadb:
    build: requirements/mariadb
    image: mariadb:oo
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart:
      - on_failure

  redis:
    build: requirements/bonus/redis
    image: redis:oo
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - inception
    restart:
      - on_failure

  protainer:
    build: requirements/bonus/portainer
    image: portainer:oo
    container_name: portainer
    ports:
      - 9443:9443
    networks:
      - inception
    restart:
      - on_failure

  adminer:
    build: requirements/bonus/adminer
    image: adminer:oo
    container_name: adminer
    ports:
      - 8080:8080
    networks: 
      - inception
    restart:
      - on_failure

  pfe:
    build: requirements/bonus/pfe
    image: pfe:oo
    container_name: pfe
    ports:
      - 8008:8008
    networks:
      - inception
    restart:
      - on_failure

volumes:
  db:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      device: /home/$USER42/mariadb
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      device: /home/$USER42/wordpress
      type: none

  pfe:
    name: pfe
    driver: local
    driver_opts:
      o: bind
      device: /home/$USER42/pfe
      type: none

networks:
  inception:
    driver: bridge
