#!/bin/bash


service mariadb start
mysql -e "CREATE DATABASE IF NOT EXISTS $MARIADB_DATABASE"
mysql -e "CREATE USER IF NOT EXISTS $USER1@% IDENTIFIED BY $PASS1"mysql -e "CREATE USER IF NOT EXISTS $USER1@% IDENTIFIED BY $PASS1"
mysql -e "CREATE USER IF NOT EXISTS $USER1@% IDENTIFIED BY $PASS1"mysql -e "CREATE USER IF NOT EXISTS $USER2@% IDENTIFIED BY $PASS2"
mysql -e "GRANT ALL ON $INCEPTION_MYSQL_DATABASE.* TO $INCEPTION_MYSQL_USER@%;"
mysqld --bind-address=0.0.0.0 --port=3306 --user=root